export * from './aviso-validacao-interface';
export * from './contribuicao-esquema-interface';
export * from './definicao-propriedade-interface';
export * from './erro-compreensao-interface';
export * from './erro-validacao-interface';
export * from './propriedade-compreendida-interface';
export * from './resultado-compreensao-interface';
export * from './resultado-validacao-interface';
export * from './sistema-arquivos-descoberta-interface';
